on:
  workflow_call:
    inputs:
      app:
        description: 'Application à publier'
        required: true
        type: string

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy:
    name: Crée l'image et publie
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Affiche le contenu du fichier VERSION
        run: echo "container_version=$(cat ${{ inputs.app }}/VERSION)"

      - name: Set version number
        run: echo "container_version=$(cat ${{ inputs.app }}/VERSION)" >> $GITHUB_ENV

      - name: Affiche le numéro de version de l'environnement
        run: echo "env.container_version -> ${{ env.container_version }}"

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push ${{ inputs.app }} Docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.app }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ inputs.app }}:latest
            ghcr.io/${{ github.repository }}/${{ inputs.app }}:${{ env.container_version }}