on:
  workflow_call:
    inputs:
      app:
        description: 'Application à publier'
        required: true
        type: string
      version:
        description: 'Tag supplémentaire Docker à appliquer'
        required: false
        type: string

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy:
    name: Crée l'image et publie
    runs-on: ubuntu-latest

    steps:

      - name: Affiche le type d'évènement déclencheur
        run: echo "github.event_name -> ${{ github.event_name }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sélectionne le numéro de version
        run: |
          version_from_container=${{ inputs.version }}
          echo "numéro de version récupéré sur le container=${version_from_container}"
          version_from_file=$(cat ${{ inputs.app }}/VERSION)
          echo "numéro de version récupéré sur le fichier VERSION=${version_from_file}"
          container_version="${version_from_container:-$version_from_file}"
          echo "container_version=${container_version}"
          echo "container_version=${container_version}" >> $GITHUB_ENV

      - name: Affiche le numéro de version de l'environnement
        run: |
          echo "env.container_version -> ${{ env.container_version }}"
          echo "container_version -> ${container_version}"

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Push ${{ inputs.app }} Docker image'
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.app }}
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ inputs.app }}:latest
            ghcr.io/${{ github.repository }}/${{ inputs.app }}:${{ env.container_version }}
