name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  call-workflow-passing-data:
    uses: signaux-faibles/conteneurs/.github/workflows/build-3rd-app-and-publish.yml@master
    with:
      app: gollum