name: Publie Keycloak dans le registre Docker

on:
  push:
    paths: [ keycloak/** ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Affiche le numéro de version de keycloak
        run: echo "keycloak_version=v$(cat keycloak/Dockerfile | head -n 1 | cut -d ':' -f 2)"

      - name: Fixe le numéro de version de keycloak
        run: echo "keycloak_version=v$(cat keycloak/Dockerfile | head -n 1 | cut -d ':' -f 2)" >> $GITHUB_ENV
    outputs:
      keycloak_version: ${{ env.keycloak_version }}

  call-workflow-passing-data:
    needs: fetch_version
    uses: signaux-faibles/conteneurs/.github/workflows/build-3rd-app-and-publish.yml@master
    with:
      app: keycloak
      version: ${{ needs.fetch_version.outputs.keycloak_version }}
