name: Publie Keycloak dans le registre Docker

on:
  push:
    paths: [ keycloak/** ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Récupère le numéro de version de keycloak
        run: echo "keycloak_version=v$(cat keycloak/Dockerfile | head -n 1 | cut -d ':' -f 2)" >> $GITHUB_ENV

  call-workflow-passing-data:
    needs: fetch-version
    uses: signaux-faibles/conteneurs/.github/workflows/build-3rd-app-and-publish.yml@master
    with:
      app: keycloak
      version: ${{ env.container_version }}
