name: Deploy Docker

on:
  push:
    paths: [ gollum/** ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  call-workflow-passing-data:
    uses: signaux-faibles/conteneurs/.github/workflows/build-3rd-app-and-publish.yml@master
    with:
      app: gollum