name: Publie PostgreSQL+pgparquet dans le registre Docker

on:
  push:
    paths: [ postgresql-pgparquet/** ]
  # Permet de lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: signaux-faibles/conteneurs/.github/workflows/build-3rd-app-and-publish.yml@master
    with:
      app: postgresql-pgparquet